

<!doctype html>
  <!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
  <!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
  <!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
  <!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>gongmingqm10</title>
    <meta name="author" content="Gong Ming">
    
    <meta name="description" content="Travel to ThoughtWorks Sep 22nd, 2014 Life Life is a journey, not a destination. 人生就是在时光的隧道中不同的奔跑，在不同的环境中遇到不同的人，然后开始相同的挣扎，最后不断优秀的过程。 &hellip;">
    
    <meta name="viewport" content="width=device-width">
    
    <link rel="canonical" href="http://gongmingqm10.github.io/blog">
    <link href="/favicon.png" rel="icon">
    <link href="/stylesheets/screen.css" media="screen, projection" rel="stylesheet">
    <link href="//atom.xml" rel="alternate" title="gongmingqm10" type="application/atom+xml">
  </head>


  <body >

    <header>
      <div class="grid-wrapper">
  <div class="grid">

    <div class="grid__item two-fifths lap-four-sixths palm-one-whole">
  <a href="/" class="site-title">gongmingqm10</a>
</div>

<div class="grid__item three-fifths lap-two-sixths palm-one-whole">
  <nav>
    <input type="checkbox" id="toggle">
<label for="toggle" class="toggle" data-open="Main Menu" data-close="Close Menu"></label>
<ul class="menu pull-right">
  <li><a href="/">Blog</a></li>
  <li><a href="/blog/archives/">Archives</a></li>
</ul>
  </nav>
</div>

  </div>
</div>
    </header>

    

    <div class="grid-wrapper">
      <div class="grid grid-center">
        
        <div class="grid__item two-thirds lap-one-whole palm-one-whole">
        

          


  
  <article class="listing">
    <header>
  
  <h1 class="beta">
    <a href="/blog/2014/09/22/travel-to-thoughtworks/">Travel to ThoughtWorks</a>
  </h1>
  

  
  <div class="meta clearfix">
    








  


<time class="pull-left" datetime="2014-09-22T10:39:01+08:00" pubdate data-updated="true"><i class="icon-calendar"></i> Sep 22<span>nd</span>, 2014</time>
    



  
  <div class="pull-left">
    <i class="icon-tags"></i>
    <ul class="tags unstyled">
    
      <li><a href="/blog/categories/Life/">Life</a></li>
    
    </ul>
  </div>
  

    
  </div>
  
</header>




  <blockquote><p>Life is a journey, not a destination.</p></blockquote>

<p>人生就是在时光的隧道中不同的奔跑，在不同的环境中遇到不同的人，然后开始相同的挣扎，最后不断优秀的过程。加入ThoughtWorks一月有余，期间经历了一些事情，趁着On beach的时光对其进行一些沉淀，若干年后作为记忆的时光进行回忆品味。</p>

<h3>面试</h3>

<p>===
转眼已是金秋时节，又是一年校招季。距离上次面试也已经快一年的距离了，时间总是走得如此之快。想起去年奔走在各个公司的面试宣讲会上。然后在人山人海中投着一遍遍的简历，然后在有幸的面试中都会被无情的刷掉。这种落差也许只有自己知道，这种期望与失望的矛盾混杂在现实的残酷与理想的丰满中。最后却冷不丁的进了ThoughtWorks的终面，经历了Quiz Test， Code Homework，Tech Interview， HR Interview，最后进到了Group Discussion。于是我用着不太顺畅的普通话讲述着 &ldquo;Why ThoughtWorks should Hire Me&#8221;，我不要会演讲，这种public speech对于我来说更是显得有点困难，但是坚持就意味着胜利。然后意外的进入了ThoughtWorks Graduate的阵营。毕业生都是将要离开学校，而第一份工作也总会决定他们一生的状态。于是凭借着自己的感觉放弃了上海那个温暖的团队，决定在这个Geek闻名的公司里面开启新的学习生涯。毕业季的日子终究是平淡的，于是也就选择了来实习。</p>

<h3>实习</h3>

<p>只身一人来到西安实习，这个第一次到来的城市总是能让我感到陌生，于是以最快的速度找好了租房，最后终于处于一个暂时安定的状态。实习之初的日子是难熬的，意味着你必须抛弃之前自己的所长来开始接受一些完全陌生的技术，接触一个完全陌生的团队，然后建立彼此之间的信任又要花费你很长时间。难熬的日子总会让你变得话很少，因为缺少了自信，自己甚至胆怯于说话。生活之余更是和大家缺少沟通。以至于大家甚至怀疑我能不能熬过这个实习阶段。我是个慢性子的人，慢慢的真实的我开始显现出来，除了一方面对技术的熟悉，另外一方面更是和大家的熟悉。这种融入集体的感觉是奇妙的，枯燥的工作开始变得乐趣横生。也许人生就是一个涅槃的过程，对于我而言尤其如此。每次到达一个新地方，我总得花上一个月得时间建立这种与人与物之间的情感。实习结束，自己开始接触Web，接触Ruby，接触AngularJS。总体而言还是很酷的。</p>

<h3>TWU</h3>

<p>TWU是我对于TW公司最期待的部分，人生就是一所大学，刚入职的我们也被送到印度进行为期五周的培训。都说印度是个开挂的城市，于是我们对印度也有了部分期待，期待之余也会有部分顾虑，对未知挑战的一种胆怯。终于在8月初出发了，我们备齐了传说种的老干妈和方便面，三拨人马分别从西安、成都、武汉奔赴北京，九人印度行就这样无声无息开始了。经历一系列的波折之后，我们终于在次日早上到达了Pune，印度这个城市没有我想像中的那么好，但是却是蛮有特色的。异国文化开始漫延开来，咖喱也沾上了我们的衣裳。</p>

<p>虽然有前辈们的前车之鉴与印度攻略，但是到了印度还是极度不适应，尤其是对这边的食物，我不能理解这种糊状的蔬菜的美味之初，不能理解咖喱的味道。我们操持着一口老干妈味道的英语开始了第一周的生活。第一周的培训主要以小组讨论为主，在天朝活惯了的我们显然很难参与老外激烈的讨论当中，于是讨论成为了我最痛苦的经历。这种经历源于语言的差异，交流是个很重要的东西，我们暂时还没适应English。</p>

<p>培训时的不积极表现是伴随着很深重的压力的，压力大部分源于我们自身。看着别人都交流甚欢，我们在一旁以疑惑的眼神看着眼前的一切，这样子真的不好。这是个Change yourself的过程，这种环境迫使我们去改变，迫使我们去融入。于是我们不得不尽量在可以发言的场合多发言，以弥补小组讨论中的不佳表现。第一周的大家都是沉闷的，大家都是有压力的。我们还是喜欢扎堆，但是对于Change却各有各自不同的看法。</p>

<p>大家以不同的状态度过了第一周，这个噩梦般的第一周。周末也终于不是让我们闲着，各种活动都等着我们，晚上回去躺在床上就不知不觉睡着了。对于我们来说，真的有点辛苦。这段时间甚至产生一个疯狂的想法，逃离印度，赶紧回国。总觉得自己的国家才是最温暖的庇护。现在的我们像个游离的人在世界的某个角落中神伤。随着时间的流逝，各种不适应开始缓解，我们开始抛弃了老干妈，开始吃着这边有名的Paratha，也会在某个空闲的晚上跑到Phoenix mall大吃一顿，这里的一顿普通的中国式的面条都可以让我们快乐一晚上。</p>

<p>除了每周的培训，我们还不得不和自己的Coach一起制定每周的Goal，Goal是我们一周最基本的任务，我们必须找时间完成。这成为了我们的一周的追求。Goal的设立从社交到社会公正到个人的学习，贯穿了公司Pillar 3 文化，这种文化是每个Twer必须接受和认同的。除了这些目标，我个人最大的两个挑战在于准备一次meaningful的LunchAndLearn，准备好一次Pecha Chucha。这种Pechu Chucha是对自己 public speech演讲能力的锻炼，演讲作为我的薄弱环节。从选择到PPT到准备演讲，花费可我不少时间和精力。好在最后在自己的努力下，这两项speech的效果都还不差。事后发现，通过这两次的锻炼，我开始不惧怕在公众场合说英语，更不会怯场了。感谢这个平台，这个挑战。</p>

<p>培训及演讲之余，我们后期的大部分工作时间都是在项目中度过，和不同文化不同背景的同时Pair编程是个很快乐的事情，好在我们来之前对于项目的技术栈有过相关的了解，我们在做Story的时侯也不至于存在太大的问题。实现手段是一方面，收获最大的还是Story的生命周期，以及作业规范，怎样成为一名符合ThoughtWorks要求的规范的Dev，我们尚在不断的学习中。学习之余，我们仍有大部分时间来进行技术相关的Dojo，对重构等的学习更是让自己受益匪浅。更增加了自己相关的专业兴趣。也增加了对软件质量代码质量的认同。</p>

<p>有人说我们来印度是来玩的，是的，除了公司带我们出去玩。我们在Yan的组织下还坐上了传说中有挂票的印度火车去孟买玩。车上也是人山人海，车上的环境也是各种味道。坐上火车穿山越岭去远方的感觉真好，我们穿过了印度的城市，穿过了印度的贫民窟，穿过了隧道，越过了山谷。我坐在火车门旁边，听着音乐，戴着耳机，任凭风吹过我的身体，任凭满眼的景色逝去，这是一种特殊的心境和状态。和大家在一起的感觉也真好，各种逗，各种笑话，各种经典，一段美好的时光永远记录在印度。</p>

<p>结束的TWU，我们准备回国了。一方面有点对印度的不舍，对朝夕相处五周的同事的不舍，更有着对异国文化的不舍与眷念。最后我们踏上了旅途，回国之前我们不忘在免税店大淘一番，看着某些奢侈品才觉得钱花得挺快赚得挺难。也有点明白为什么中国大妈喜欢在国外大淘特淘了，大家总喜欢与国内得对比，总觉得国外得便宜，买了这些就等于赚了。我也不例外。</p>

<p>回来了，感觉真好&hellip;</p>

<h3>现在</h3>

<p>回公司一周有余，回首过去一周基本处于游离状态，尚未真正加入项目组，更别谈能够和团队有所融合。发现对之前实习的项目组倒是有很多的怀念，人总是怀旧的。也希望我能够快速的加入加入到现在的项目组中，真正找到归宿感。</p>

<p>BTW, 挺怀念去印度的九个小伙伴以及和大家度过的岁月</p>


  </article>
  <hr>

  
  <article class="listing">
    <header>
  
  <h1 class="beta">
    <a href="/blog/2014/09/16/android-best-practice/">Android best practice</a>
  </h1>
  

  
  <div class="meta clearfix">
    








  


<time class="pull-left" datetime="2014-09-16T10:41:25+08:00" pubdate data-updated="true"><i class="icon-calendar"></i> Sep 16<span>th</span>, 2014</time>
    



  
  <div class="pull-left">
    <i class="icon-tags"></i>
    <ul class="tags unstyled">
    
      <li><a href="/blog/categories/android/">android</a></li>
    
    </ul>
  </div>
  

    
  </div>
  
</header>




  <h1>Android 最佳实践</h1>

<p>从事android开发两年有余，但是自己的代码自己却不太敢恭维。于是我不得不来改善我的Android程序，为了使它变得更加的稳固，更加的专业。本文旁征博引，多处观点都是Google之，结合自己的经验总结了Android开发中的一些最佳实践，厚积方能博发，多积累多学习才能多进步。</p>

<h3>Android Activity 的生命周期</h3>

<p>生命周期（Lifecycle）描述的是Android一个页面从开始创建到消亡的整个过程。伴随着一系列对象的创建及消失，涵盖着整个页面所包含的业务逻辑。以及与用户之间的交互，接受用户的输入并返回输出信息给用户。</p>

<p><img src="http://i.imgur.com/rPrTr.png" alt="Android Lifecycle" /></p>

<p>从其生命流程图中，我们可以看到Android单个Activity的生命周期主要为 onCreate &ndash;> onStart &ndash;> onResume &ndash;> Activity Running &ndash;> onPause &ndash;> onStop &ndash;> onDestroy. 通常单个App是由诸多的Activity组成的，一般情况我们肉眼所见的一个页面就是一个Activity，我们也经常再APP中点击Button或者Back，于是我们实现了Activity之间的切换。</p>

<h5>1. onCreate()与onDestroy()</h5>

<p>如何理解onCreate()呢？首先通过来自Google的官方解释来看onCreate()方法的作用：</p>

<blockquote><p>onCreate(Bundle) is where you initialize your activity. Most importantly, here you will usually call setContentView(int) with a layout resource defining your UI, and using findViewById(int) to retrieve the widgets in that UI that you need to interact with programmatically</p></blockquote>

<p>所以onCreate方法主要用于初始化我们的Activity。在onCreate()方法中，我们通过setContentView(int)来为当前的Activity指定对应的View， 然后通过findViewById(int)通过id检索当前View中的组件。至此，onCreate()的一些基本的初始化工作完成, Activity全局的初始化工作应该都在onCreate()中完成，这些初始化状态一直会被保存直到onDestroy()被调用，也就意味着Activity消亡。</p>

<p>细心观察发现，Activity的onCreate(Bundle)函数会有一个Bundle类型的参数savedInstanceState，通过这个meaningful的名字可以看到此参数主要用于使用之前保存的数据。</p>

<p>与onCreate()对应的方法是onDestroy(), 后者主要是Activity被销毁时会被执行的方法，当我们调用this.finish()手动结束当前的Activity, 此时onDestroy()会被回调，我们可以在这里面做一些程序被销毁前的保存性操作。</p>

<h5>2. onStart()与onStop()</h5>

<p>这两种状态一般出现在，当用户从Activity A 跳转到Activity B 中，此时Activity A 的 onStop函数会被回调，此时Activity A 被压入到堆栈中，并处于不可见状态。一旦用户结束Activity B, 再次进入Activity A 中，系统会重新调用onRestart()和onStart()函数，于是这个Activity重新被唤醒。</p>

<h5>3. onResume()与onPause()</h5>

<p>通过字面意思理解为Activity的恢复和停止，一个典型的例子是APP运行过程中突然有电话或者闹铃，以至于当前的Activity被其他的Activity覆盖，这种情况下会触发onResume()和onPause()事件，当然如果APP经历onStart()和onStop()事件，也必然会先经过onResume()和onPause()事件。生命周期的流程图如上图所示，其形成的是一个完成的闭路。</p>

<p> ===
通过应用程序的一套完整的Lifecycle，Android保证了APP在手机上进行良好的运行，并且运行过程互不干扰。Android生命周期的存在也表明在APP开发中，应该使Activity功能彼此对应，在onStart()中注册了某些事件，在onStop()中就应该进行反注册，例如地图开发中的GPS定位，就需要在onStart中进行注册，而在onStop()中进行反注册。还有一些网络访问回调也存在类似的情形，都需要我们在APP开发中注意，确保APP以最佳的状态运行。</p>

<h3>Activity的职能－避免Activity类承载太多职能</h3>

<p>Activity作为Android的Controller，直接负载着与用户的交互过程。开发中Activitiy很容易由于大量的动画，布局等操作而变得臃肿，特别使业务逻辑渐渐复杂时，Activity过大的代码量增加了维护成本，甚至开发者自己都很难读懂这个Activity真正的含义。为了避免这种情况，我们要尽量将纯UI布局和动画逻辑分离到第三方类中，在Activity与用户交互过程中，一旦需要某些UI操作和动画表现等，直接对其相关的UI布局等进行调用即可。我们的Activity只作为真正的Controller，控制着接收用户输入以及反馈输出，至于中间的逻辑则完全可以交给“Presenter”调用。</p>

<h3>Android布局多屏适配</h3>

<p>Android由于设备众多，分辨率众多，不同厂家定制的SDK也增加了适配成本。所以我们开发过程，就不应该使用太过绝对的布局，而应该尽量使用相对布局。过于绝对的布局可能在当前设备上表现良好，一旦在其他机器上运行则可能会出现布局错乱的问题。布局时也要避免View之间的深嵌套，根据你的设计图选择合适的布局方式，过重的布局会拖慢页面的渲染速度，进而影响整个APP的性能表现。</p>

<h3>用Fragment代替Activity</h3>

<p>自Android4.0之后，Android开始使用Fragment，并保持不断更新中。简言之，Fragment也是可以直接代替Activity的Controller，Fragment主要是为了适配手机和平板而生的，Fragment在手机上和Activity的表现无异，但是在平板上却可以以类似于组件的形式表现出来，这种形式更适合平板的大屏显示方式。Fragment让我们不用去同时维护手机和平板上的两套代码，方便了开发过程。</p>

<h3>MVC最佳实践</h3>

<p>和Web开发中的MVC框架类似，我们同样可以对APP进行MVC化。具体而言，Activity是我们的Controller控制器，而对数据的读取与查询等具体语句则应该通过DataManager进行处理，类似于我们通常所说的Service，Service不直接和界面进行交互。用户的交互都是与Activity发生的，Service会提供一些数据读取相关的方法，以供Activity调用。</p>

<p>===
本文抛砖引玉，参考别人的文章，结合自己的实践经历总结了一些实践性的经验。个中不足，烦请大家不吝赐教，当然更欢迎大家一起交流。</p>

<p>文章参考：<a href="http://clayallsopp.com/posts/android-best-practices-tips/">http://clayallsopp.com/posts/android-best-practices-tips/</a></p>


  </article>
  <hr>

  
  <article class="listing">
    <header>
  
  <h1 class="beta">
    <a href="/blog/2014/08/17/mybait-migration-session/">mybait migration session</a>
  </h1>
  

  
  <div class="meta clearfix">
    








  


<time class="pull-left" datetime="2014-08-17T20:50:41+08:00" pubdate data-updated="true"><i class="icon-calendar"></i> Aug 17<span>th</span>, 2014</time>
    



  
  <div class="pull-left">
    <i class="icon-tags"></i>
    <ul class="tags unstyled">
    
      <li><a href="/blog/categories/database/">database</a></li>
    
    </ul>
  </div>
  

    
  </div>
  
</header>




  <h2>Mybatis Migration 初探</h2>

<p>持续交付项目中，项目会不断的迭代上线，这是会出现数据库的改动问题。在一个还未上线的项目中，我更改数据库可以使用简单的直接对sql进行更改，但是面对一个已投入使用的系统而言，每次部署都对数据库进行init显得有点不太可能。于是便有了数据库Migration的诞生。</p>

<p>我所在的项目是SpringMVC配合Mybatis的开发框架。作为一个数据库集成框架，Mybatis在使用上还是比较方便的。言归正传，为了项目需要，于是便开始了Mybatis Migration的初探，文章中出现的不妥之处还请大家不吝赐教。</p>

<h4>Mybatis Migration 安装</h4>

<p>安装过程主要参照Mybatis的官网： <a href="http://mybatis.github.io/migrations/index.html">http://mybatis.github.io/migrations/index.html</a>，以及Mybatis源代码授权地址: <a href="https://github.com/mybatis/migrations">https://github.com/mybatis/migrations</a>，参照github上的README文件可以轻易的完成其安装过程。README文件中所有的Mybatis包可以直接在其Git repo的releases中找到，我选择了3.2.0进行下载安装。安装完成后就可以直接在terminal中运行migrate相关的命令了。</p>

<h4>Mybatus Migration 初始化</h4>

<pre><code>minggong:migration-test minggong$ migrate init
------------------------------------------------------------------------
-- MyBatis Migrations - init
------------------------------------------------------------------------
Initializing: .
Creating: environments
Creating: scripts
Creating: drivers
Creating: README
Creating: development.properties
Creating: bootstrap.sql
Creating: 20140817132704_create_changelog.sql
Creating: 20140817132705_first_migration.sql
Done!

------------------------------------------------------------------------
-- MyBatis Migrations SUCCESS
-- Total time: 2s
-- Finished at: Sun Aug 17 18:57:05 GMT+05:30 2014
-- Final Memory: 3M/493M
------------------------------------------------------------------------
minggong:migration-test minggong$ ls
README      drivers     environments    scripts
</code></pre>

<p>初始化之后的目录下面会自动生成一些和Migration相关的项目文件及目录 README, drivers, environments, scripts。drivers中放置连接数据库需要的jdbc，environments主要放置连接数据库的地址以及授权信息等，scripts目录下则放置数据库相关的sql，init的时候就已经生成了上述显示的create_changelog.sql和first_migration.sql文件。</p>

<p>为了以实例说明问题，本次测试采用了mysql数据库，从mysql官网下载了<code>mysql-connector-java-5.1.32</code>，并对environment的数据库信息进行了简单的配置，配置如下：</p>

<pre><code>## JDBC connection properties.
driver=com.mysql.jdbc.Driver
url=jdbc:mysql://localhost:3306/arctic
username=root
password=
</code></pre>

<p>这里的arctic是已经存在本地的一个mysql数据库。</p>

<h4>Migrate bootstrap</h4>

<pre><code>minggong:migration-test minggong$ migrate bootstrap
------------------------------------------------------------------------
-- MyBatis Migrations - bootstrap
------------------------------------------------------------------------
========== Applying: bootstrap.sql =============================================

------------------------------------------------------------------------
-- MyBatis Migrations SUCCESS
-- Total time: 0s
-- Finished at: Sun Aug 17 19:43:29 GMT+05:30 2014
-- Final Memory: 11M/493M
------------------------------------------------------------------------
</code></pre>

<p>运行之后，scripts文件中将会生成另外一个bootstrap文件。主要可以进行一些数据库初始化工作。</p>

<h4>Migrate new</h4>

<p><code>new</code>命令能够创建新的sql脚本，我们只需要填充数据表结构信息，便可以方便的创建我们所需的数据表</p>

<pre><code>minggong:migration-test minggong$ migrate new "create blog table"
------------------------------------------------------------------------
-- MyBatis Migrations - new
------------------------------------------------------------------------
Creating: 20140817142201_create_blog_table.sql
Done!

------------------------------------------------------------------------
-- MyBatis Migrations SUCCESS
-- Total time: 1s
-- Finished at: Sun Aug 17 19:52:01 GMT+05:30 2014
-- Final Memory: 3M/493M
------------------------------------------------------------------------
</code></pre>

<p>scripts文件夹中会创建带有时间戳的sql文件：<code>20140817142201_create_blog_table.sql</code>， 其内容如下：</p>

<pre><code>-- // create blog table
-- Migration SQL that makes the change goes here.

-- //@UNDO
-- SQL to undo the change goes here.
</code></pre>

<p>文件内容主要包含<code>create table</code>和<code>undo</code>，分别表示表的创建和删除命令：</p>

<pre><code>-- // create blog table
-- Migration SQL that makes the change goes here.
CREATE TABLE BLOG (
  ID INT,
  NAME VARCHAR(255),
  PRIMARY KEY(ID)
);
-- //@UNDO
-- SQL to undo the change goes here.
DROP TABLE BLOG;
</code></pre>

<p>已经将表结构写在了sql里面，那么怎样执行这个脚本，从而改变数据库中的表结构呢。首先我们需要了解当前数据库的状态。</p>

<h4>Migrate status</h4>

<pre><code>minggong:migration-test minggong$ migrate status
------------------------------------------------------------------------
-- MyBatis Migrations - status
------------------------------------------------------------------------
ID             Applied At          Description
================================================================================
20140817132704    ...pending...    create changelog
20140817132705    ...pending...    first migration
20140817142201    ...pending...    create blog table

------------------------------------------------------------------------
-- MyBatis Migrations SUCCESS
-- Total time: 0s
-- Finished at: Sun Aug 17 20:21:06 GMT+05:30 2014
-- Final Memory: 11M/493M
------------------------------------------------------------------------
</code></pre>

<p>由于我们没有运行过migration, 所以所有migration脚本都处于<code>pending</code>状态，包括changelog table本身。当我们运行<code>migrate up</code>命令之后，脚本的状态便会发生相应的改变。</p>

<h4>Migrate up, down</h4>

<p>为了显示更多up, down以及后续的version操作，再次新建一个数据表<code>migrate new 'create table author'</code>此时的author和blog应该都处于pending状态。</p>

<pre><code>minggong:migration-test minggong$ migrate status
------------------------------------------------------------------------
-- MyBatis Migrations - status
------------------------------------------------------------------------
ID             Applied At          Description
================================================================================
20140817132704    ...pending...    create changelog
20140817132705    ...pending...    first migration
20140817142201    ...pending...    create blog table
20140817154537    ...pending...    create table author

------------------------------------------------------------------------
-- MyBatis Migrations SUCCESS
-- Total time: 0s
-- Finished at: Sun Aug 17 21:21:49 GMT+05:30 2014
-- Final Memory: 11M/493M
------------------------------------------------------------------------
minggong:migration-test minggong$ migrate up
------------------------------------------------------------------------
-- MyBatis Migrations - up
------------------------------------------------------------------------
========== Applying: 20140817132704_create_changelog.sql =======================
--  Create Changelog
-- Default DDL for changelog table that will keep
-- a record of the migrations that have been run.
-- You can modify this to suit your database before
-- running your first migration.
-- Be sure that ID and DESCRIPTION fields exist in
-- BigInteger and String compatible fields respectively.
CREATE TABLE CHANGELOG (
ID NUMERIC(20,0) NOT NULL,
APPLIED_AT VARCHAR(25) NOT NULL,
DESCRIPTION VARCHAR(255) NOT NULL
)

ALTER TABLE CHANGELOG
ADD CONSTRAINT PK_CHANGELOG
PRIMARY KEY (id)


========== Applying: 20140817132705_first_migration.sql ========================
--  First migration.
-- Migration SQL that makes the change goes here.

========== Applying: 20140817142201_create_blog_table.sql ======================
--  create blog table
-- Migration SQL that makes the change goes here.

========== Applying: 20140817154537_create_table_author.sql ====================
--  create table author
-- Migration SQL that makes the change goes here.

------------------------------------------------------------------------
-- MyBatis Migrations SUCCESS
-- Total time: 0s
-- Finished at: Sun Aug 17 21:22:17 GMT+05:30 2014
-- Final Memory: 13M/493M
------------------------------------------------------------------------
</code></pre>

<p><code>migrate up</code>命令会将所有的sql进行up,所有处于pending状态的SQL脚本都会进行执行。对应的<code>migrate down</code>则是undo sql脚本的执行，也就是执行sql中用户自定义的UNDO部分。不同的是<code>migrate down</code>只能回退一步，所以回退到初始状态则需要运行多次的<code>migrate down</code>操作。当然也可以直接指定参数，本例中我们指定回退4步<code>migrate down 4</code>:</p>

<pre><code>minggong:migration-test minggong$ migrate status
------------------------------------------------------------------------
-- MyBatis Migrations - status
------------------------------------------------------------------------
ID             Applied At          Description
================================================================================
20140817132704 2014-08-17 21:22:17 create changelog
20140817132705 2014-08-17 21:22:17 first migration
20140817142201 2014-08-17 21:22:17 create blog table
20140817154537 2014-08-17 21:26:01 create table author

------------------------------------------------------------------------
-- MyBatis Migrations SUCCESS
-- Total time: 0s
-- Finished at: Sun Aug 17 21:26:07 GMT+05:30 2014
-- Final Memory: 11M/493M
------------------------------------------------------------------------
minggong:migration-test minggong$ migrate down 4
------------------------------------------------------------------------
-- MyBatis Migrations - down
------------------------------------------------------------------------
========== Undoing: 20140817154537_create_table_author.sql =====================
-- @UNDO
-- SQL to undo the change goes here.

========== Undoing: 20140817142201_create_blog_table.sql =======================
-- @UNDO
-- SQL to undo the change goes here.

========== Undoing: 20140817132705_first_migration.sql =========================
-- @UNDO
-- SQL to undo the change goes here.

========== Undoing: 20140817132704_create_changelog.sql ========================
-- @UNDO
DROP TABLE CHANGELOG

Changelog doesn't exist. No further migrations will be undone (normal for the last migration).

------------------------------------------------------------------------
-- MyBatis Migrations SUCCESS
-- Total time: 0s
-- Finished at: Sun Aug 17 21:29:53 GMT+05:30 2014
-- Final Memory: 14M/493M
------------------------------------------------------------------------
minggong:migration-test minggong$ migrate status
------------------------------------------------------------------------
-- MyBatis Migrations - status
------------------------------------------------------------------------
ID             Applied At          Description
================================================================================
20140817132704    ...pending...    create changelog
20140817132705    ...pending...    first migration
20140817142201    ...pending...    create blog table
20140817154537    ...pending...    create table author

------------------------------------------------------------------------
-- MyBatis Migrations SUCCESS
-- Total time: 0s
-- Finished at: Sun Aug 17 21:30:09 GMT+05:30 2014
-- Final Memory: 11M/493M
------------------------------------------------------------------------
</code></pre>

<h4>Migrate verison</h4>

<p>回滚到指定的version状态，后面需要加上version的ID： <code>migrate verison 20140817132705</code></p>

<pre><code>minggong:migration-test minggong$ migrate status
------------------------------------------------------------------------
-- MyBatis Migrations - status
------------------------------------------------------------------------
ID             Applied At          Description
================================================================================
20140817132704 2014-08-17 22:23:05 create changelog
20140817132705 2014-08-17 22:23:25 first migration
20140817142201 2014-08-17 22:23:25 create blog table
20140817154537 2014-08-17 22:23:25 create table author
20140817164341 2014-08-17 22:23:25 create table book

------------------------------------------------------------------------
-- MyBatis Migrations SUCCESS
-- Total time: 0s
-- Finished at: Sun Aug 17 22:23:36 GMT+05:30 2014
-- Final Memory: 11M/493M
------------------------------------------------------------------------
minggong:migration-test minggong$ migrate version 20140817142201
------------------------------------------------------------------------
-- MyBatis Migrations - version
------------------------------------------------------------------------
Downgrading to: 20140817142201
========== Undoing: 20140817164341_create_table_book.sql =======================
-- @UNDO
-- SQL to undo the change goes here.

========== Undoing: 20140817154537_create_table_author.sql =====================
-- @UNDO
-- SQL to undo the change goes here.


------------------------------------------------------------------------
-- MyBatis Migrations SUCCESS
-- Total time: 0s
-- Finished at: Sun Aug 17 22:23:43 GMT+05:30 2014
-- Final Memory: 13M/493M
------------------------------------------------------------------------
minggong:migration-test minggong$ migrate status
------------------------------------------------------------------------
-- MyBatis Migrations - status
------------------------------------------------------------------------
ID             Applied At          Description
================================================================================
20140817132704 2014-08-17 22:23:05 create changelog
20140817132705 2014-08-17 22:23:25 first migration
20140817142201 2014-08-17 22:23:25 create blog table
20140817154537    ...pending...    create table author
20140817164341    ...pending...    create table book

------------------------------------------------------------------------
-- MyBatis Migrations SUCCESS
-- Total time: 0s
-- Finished at: Sun Aug 17 22:23:47 GMT+05:30 2014
-- Final Memory: 11M/493M
------------------------------------------------------------------------
</code></pre>

<h4>Migrate pending</h4>

<p><code>migrate up</code> 命令只能向上upgrade，而在多人合作中如果migration sql脚本先创建但是后提交，同步到一台服务器上就有可能出现中间某个文件处于<code>pending</code>状态，这时使用<code>migrate up</code>是不能使其执行的。</p>

<p>这种情况如果这个sql基本和其他sql无依赖时，可以直接使用<code>migrate up</code>使处于pending状态的脚本被执行。官方解释这是不推荐的做法。另外一种做法是使用<code>migrate version [ID]</code>回到pending版本之前的状态，然后再次执行<code>migrate up</code>，从而完成整个执行操作，这种做法是推荐的比较安全的。</p>

<h4>Migrate script</h4>

<p>使用方法为<code>migrate script &lt;V1&gt; &lt;V2&gt; &gt; file.sql</code></p>

<p><code>migrate 20140817142201 20140817164341 &gt; do.sql</code>这个do脚本的执行将会应用上述两个状态的执行author和book。</p>

<p><code>migrate 20140817164341 20140817142201 &gt; undo.sql</code> 这个将undo脚本执行可以回滚V1和V2之间的即上述状态。</p>

<p>如果要在首尾之间回滚，则可以用 0 代替原始版本ID</p>

<p><code>migrate 0 20140817164341 &gt; do.sql</code></p>

<p><code>migrate 20140817164341 0 &gt; undo.sql</code></p>

<hr />

<p>但是对于上述的script脚本直接使用 migrate do.sql执行却一直报错！官方也没有对单个的脚本执行有说明。后续弄清楚了再补充上来。</p>


  </article>
  <hr>

  
  <article class="listing">
    <header>
  
  <h1 class="beta">
    <a href="/blog/2014/03/19/fontello-shi-yong-xin-de/">Fontello 使用心得</a>
  </h1>
  

  
  <div class="meta clearfix">
    








  


<time class="pull-left" datetime="2014-03-19T08:19:49+08:00" pubdate data-updated="true"><i class="icon-calendar"></i> Mar 19<span>th</span>, 2014</time>
    



  
  <div class="pull-left">
    <i class="icon-tags"></i>
    <ul class="tags unstyled">
    
      <li><a href="/blog/categories/Design/">Design</a></li>
    
    </ul>
  </div>
  

    
  </div>
  
</header>




<div class="entry-content clearfix">
  <h2>Overview</h2>

<p>Fontello icon generator <a href="http://fontello.com/">http://fontello.com/</a>，fontello上可以选择各种各样的常见的icon，所有的icon都是字体格式，所以对于icon的大小和颜色你都可以像使用字体一样方便的使用他们。</p>

<hr />

<p>最近尝试在构建一个rails应用，于是自然而然就想到用之前项目中的fontello图标，对于Developer来说，有了fontello和rails我开始不需要担心街面上图标或者按钮的样式问题了。</p>


  <a class="btn pull-right" href="/blog/2014/03/19/fontello-shi-yong-xin-de/">Read on &rarr;</a>
</div>

  </article>
  <hr>

  
  <article class="listing">
    <header>
  
  <h1 class="beta">
    <a href="/blog/2014/03/08/ding-can-wang-zhi-si/">订餐网之死</a>
  </h1>
  

  
  <div class="meta clearfix">
    








  


<time class="pull-left" datetime="2014-03-08T18:37:11+08:00" pubdate data-updated="true"><i class="icon-calendar"></i> Mar 8<span>th</span>, 2014</time>
    



  
  <div class="pull-left">
    <i class="icon-tags"></i>
    <ul class="tags unstyled">
    
      <li><a href="/blog/categories/产品/">产品</a></li>
    
      <li><a href="/blog/categories/创业/">创业</a></li>
    
    </ul>
  </div>
  

    
  </div>
  
</header>




<div class="entry-content clearfix">
  <h3>起源</h3>

<p>订餐网真名不详，只是为了表意故意称之为<strong>订餐网</strong>。都说文以表意，于是订餐网的本身就是为了订餐外卖做准备，这还是我刚在TW实习为了学习组内的技术栈也为了实现一点小想法进行的一次尝试。尝试的初衷很简单，为了学习。动力很简单，学好一门技术，做个web站点出来。而终点就是能够使之成为我的毕设，也作为自己对<em>创业</em>的一点尝试。在buddy的鼓励下，我真的开始在做的&hellip;也真的想把这个产品做好了。</p>


  <a class="btn pull-right" href="/blog/2014/03/08/ding-can-wang-zhi-si/">Read on &rarr;</a>
</div>

  </article>
  <hr>

  
  <article class="listing">
    <header>
  
  <h1 class="beta">
    <a href="/blog/2014/01/18/zai-railsji-cheng-mongodbkai-fa-ying-yong/">在rails集成mongodb开发应用</a>
  </h1>
  

  
  <div class="meta clearfix">
    








  


<time class="pull-left" datetime="2014-01-18T16:04:48+08:00" pubdate data-updated="true"><i class="icon-calendar"></i> Jan 18<span>th</span>, 2014</time>
    



  
  <div class="pull-left">
    <i class="icon-tags"></i>
    <ul class="tags unstyled">
    
      <li><a href="/blog/categories/rails/">rails</a></li>
    
    </ul>
  </div>
  

    
  </div>
  
</header>




<div class="entry-content clearfix">
  <p>最近尝试用rails集成mongodb开发我的第一个rails应用，用IDE直接创建project之后，发现工程默认会采用sqlite数据库。于是需要自己手工进行一些数据库配置：
如果你的app已经使用IDE建立好了，需要修改的文件有 config/application.rb 和 config/environments/development.rb</p>

<figure class='code'><figcaption><span>config/application.rb </span></figcaption>
<div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class='line-number'>1</span>
</pre></td><td class='code'><pre><code class='ruby'><span class='line'><span class="nb">require</span> <span class="s1">&#39;rails/all&#39;</span>
</span></code></pre></td></tr></table></div></figure>


<p>替换为 =></p>

<figure class='code'><figcaption><span>config/application.rb </span></figcaption>
<div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class='line-number'>1</span>
<span class='line-number'>2</span>
<span class='line-number'>3</span>
<span class='line-number'>4</span>
</pre></td><td class='code'><pre><code class='ruby'><span class='line'><span class="nb">require</span> <span class="s2">&quot;action_controller/railtie&quot;</span>
</span><span class='line'><span class="nb">require</span> <span class="s2">&quot;action_mailer/railtie&quot;</span>
</span><span class='line'><span class="nb">require</span> <span class="s2">&quot;sprockets/railtie&quot;</span>
</span><span class='line'><span class="nb">require</span> <span class="s2">&quot;rails/test_unit/railtie&quot;</span>
</span></code></pre></td></tr></table></div></figure>




<figure class='code'><figcaption><span>config/environments/development.rb </span></figcaption>
<div class="highlight"><table><tr><td class="gutter"><pre class="line-numbers"><span class='line-number'>1</span>
</pre></td><td class='code'><pre><code class='ruby'><span class='line'> <span class="c1">#config.active_record.migration_error = :page_load</span>
</span></code></pre></td></tr></table></div></figure>





  <a class="btn pull-right" href="/blog/2014/01/18/zai-railsji-cheng-mongodbkai-fa-ying-yong/">Read on &rarr;</a>
</div>

  </article>
  <hr>

        
        </div>
        
        
        <aside id="sidebar" class="grid__item one-third lap-one-whole palm-one-whole">
          <div class="grid">

  
<section class="social aside-module grid__item one-whole lap-one-half">
  <h1 class="title delta">
    Follow Me
  </h1>
  <ul class="unstyled">
    
    
    <li><a class="github" href="//github.com/gongmingqm10"><i class="icon-github"></i> Github</a></li>
    
    
    
    
    <li><a class="stackoverflow" href="//stackoverflow.com/users/gongmingqm10@gmail.com"><i class="icon-stackexchange"></i> StackOverflow</a></li>
    
    
  </ul>
</section>


  <section id="recent-posts" class="aside-module grid__item one-whole lap-one-half">
  <h1 class="title delta">Recent Posts</h1>
  <ul class="divided">
    
      <li class="post">
        <a href="/blog/2014/09/22/travel-to-thoughtworks/">Travel to ThoughtWorks</a>
      </li>
    
      <li class="post">
        <a href="/blog/2014/09/16/android-best-practice/">Android best practice</a>
      </li>
    
      <li class="post">
        <a href="/blog/2014/08/17/mybait-migration-session/">mybait migration session</a>
      </li>
    
      <li class="post">
        <a href="/blog/2014/03/19/fontello-shi-yong-xin-de/">Fontello 使用心得</a>
      </li>
    
      <li class="post">
        <a href="/blog/2014/03/08/ding-can-wang-zhi-si/">订餐网之死</a>
      </li>
    
  </ul>
</section>
<section id="tag-cloud-section" class="aside-module grid__item one-whole lap-one-half">
  <h1 class="title delta">Tag Cloud</h1>
    <span id="tag-cloud" style="font-size: 100.0% !important;"><a href='/blog/categories/android' style='font-size: 160.0%'>android(1)</a> <a href='/blog/categories/database' style='font-size: 160.0%'>database(1)</a> <a href='/blog/categories/design' style='font-size: 160.0%'>Design(1)</a> <a href='/blog/categories/life' style='font-size: 160.0%'>Life(1)</a> <a href='/blog/categories/rails' style='font-size: 160.0%'>rails(1)</a> <a href='/blog/categories/chan-pin' style='font-size: 160.0%'>产品(1)</a> <a href='/blog/categories/chuang-ye' style='font-size: 160.0%'>创业(1)</a> </span>
</section>
<section id="about me" class="aside-module grid__item one-whole lap-one-half">
  <h1 class="title delta">About Me</h1>
  <p>龚铭，目前就职于Thoughtworks，Developer一枚。热爱生活，热爱新技术。思考技术，思考人生</p>
</section>


</div>

        </aside>
        
      </div>
    </div>
    
    <footer>
      <div class="grid-wrapper">
  <div class="grid">
    <div class="grid__item">
      <p class="copyright">
	Copyright &copy; 2014 - Gong Ming -	<a href="mailto:minggong@thoughtworks.com">Contact me</a> - 
	<span class="credit">Powered by <a href="http://octopress.org">Octopress</a></span>
</p>
    </div>
  </div>
</div>

    </footer>

    <!--[if lt IE 7]>
      <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
    <![endif]-->

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="//crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/md5.js"></script>
<script defer src="/javascripts/octopress.js"></script>


<script>
  var _gaq=[['_setAccount','UA-48787063-1'],['_trackPageview']];
  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
  s.parentNode.insertBefore(g,s)}(document,'script'));
</script>











  </body>
</html>